In [1]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

c:\users\cdileepkumar\documents\02 python_practice\03 softwares\01 python\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
dataset=datasets.load_iris()
model=GaussianNB()
model.fit(dataset.data,dataset.target)
print(model)

GaussianNB(priors=None, var_smoothing=1e-09)


In [5]:
expected=dataset.target
predicted=model.predict(dataset.data)
print(metrics.classification_report(expected,predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150



In [6]:
print(metrics.confusion_matrix(expected,predicted))

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
