# Chi-Square Test
Applied when two categorical variables from a single population.

IT is Used to determine whether there is a significant association between the two categorical variables.


In [5]:
import scipy.stats as stats
import seaborn as sns
import numpy as np
dataset=sns.load_dataset('tips')
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
import pandas as pd
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [9]:
observed_values=dataset_table.values
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [12]:
val=stats.chi2_contingency(dataset_table)
val

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [16]:
expected_values=val[3]
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [22]:
no_of_rows=len(dataset_table.iloc[:,0])
no_of_cols=len(dataset_table.iloc[0,:])
degree_of_freedom=(no_of_rows-1)*(no_of_cols-1)
print("Degree of Freedom:"+str(degree_of_freedom))
alpha=0.05 # 95% Confidence Interval

Degree of Freedom:1


In [25]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:",chi_square_statistic) # This is the calculated chi square.

chi-square statistic: 0.001934818536627623


In [28]:
critical_value=chi2.ppf(q=1-alpha,df=degree_of_freedom) # THis is the value from chi square table for df=1 and this is the critical value.
print("critical value:",critical_value)

critical value: 3.841458820694124


In [36]:
#If chi2 calculated is < critical value ,then accept the Null hypothesis else Reject the Null hypothesis.
if chi_square_statistic >= critical_value:
    print("Reject Null Hypothesis ,,There is  relation between sex and smoker categorical variables")
else:
    print("Accept the Null Hypothesis ,,There is no relation between sex and smoker categorical variables")

Accept the Null Hypothesis ,,There is no relation between sex and smoker categorical variables


In [32]:
#USing P-Value we can do the same.
p_value=1-chi2.cdf(x=chi_square_statistic,df=degree_of_freedom)
print("p-value:",p_value)
print("Significant value:",alpha)
print("Degree of Freedom:",degree_of_freedom)

p-value: 0.964915107315732
Significant value: 0.05
Degree of Freedom: 1


In [35]:
if p_value <= alpha:
        print("Reject Null Hypothesis ,,There is  relation between sex and smoker categorical variables")
else:
        print("Accept the Null Hypothesis ,,There is no relation between sex and smoker categorical variables")

Accept the Null Hypothesis ,,There is no relation between sex and smoker categorical variables
